#!/bin/bash

PACKAGE=$1

if [ -z "${PACKAGE}" ]; then
    echo "Error: No package name."
    echo "Usage: ./execution <PACKAGE_NAME>"
    exit 1
fi

IP_ADDRESS=$(ifconfig en0 | grep "inet " | awk '{print $2}')
PORT=8080

echo "Setting proxy to $IP:$PORT"
adb shell settings put global http_proxy $(ipconfig getifaddr en0):8080
adb shell settings put global https_proxy $(ipconfig getifaddr en0):8080
echo "Setting proxy to $IP:$PORT successfully"

echo "-- The mitmproxy is running at ip address of $IP_ADDRESS, port = $PORT --"

FRIDA_VERSION="16.5.9"
ARCH="arm64"

if [ ! -f "frida-server-${FRIDA_VERSION}-android-${ARCH}" ]; then
    echo "Downloading frida-server..."
    wget https://github.com/frida/frida/releases/download/${FRIDA_VERSION}/frida-server-${FRIDA_VERSION}-android-${ARCH}.xz

    echo "Extracting frida-server..."
    unxz frida-server-${FRIDA_VERSION}-android-${ARCH}.xz
    chmod +x frida-server-${FRIDA_VERSION}-android-${ARCH}
fi

adb root

adb shell "pkill frida-server" 2>/dev/null || true

echo "Pushing frida-server to emulator..."
adb push frida-server-${FRIDA_VERSION}-android-${ARCH} /data/local/tmp/frida-server

adb shell "chmod 777 /data/local/tmp/frida-server"

echo "Starting frida-server inside emulator..."
adb shell "/data/local/tmp/frida-server" &

echo "Frida-server setup completed."

if [ "$1" == "-w"]; then
  mitmweb -s src/traffic-analysis.py -p ${PORT} --set block_global=false --set app_package=${PACKAGE} &
else
  mitmdump -s src/traffic-analysis.py -p ${PORT} --set block_global=false --set app_package=${PACKAGE} &
fi

MITM_PID=$!

echo "mitmproxy is running with PID: ${MITM_PID}"

frida -U -f ${PACKAGE} -l src/multiple-script.js

echo "Resetting proxy settings..."

adb shell settings put global http_proxy :0 
adb shell settings put global https_proxy :0 

echo "Proxy settings cleared. Emulator now connects directly."

kill ${MITM_PID}

echo "The process is terminated successfully"