#!/bin/bash

PACKAGE=$1

if [ -z "${PACKAGE}" ]; then
    echo "Error: No package name."
    echo "Usage: ./execution <PACKAGE_NAME>"
    exit 1
fi

IP_ADDRESS=$(ifconfig en0 | grep "inet " | awk '{print $2}')
PORT=8080

echo "-- The mitmproxy is running at ip address of $IP_ADDRESS, port = $PORT --"

FRIDA_VERSION="16.5.9"
ARCH="arm64"

if [ ! -f "frida-server-${FRIDA_VERSION}-android-${ARCH}" ]; then
    echo "Downloading frida-server..."
    wget https://github.com/frida/frida/releases/${FRIDA_VERSION}/frida-server-${FRIDA_VERSION}-android-${ARCH}.xz

    echo "Extracting frida-server..."
    unxz frida-server-${FRIDA_VERSION}-android-${ARCH}.xz
    chmod +x frida-server-${FRIDA_VERSION}-android-${ARCH}
fi

adb shell "pkill frida-server" 2>/dev/null || true

echo "Pushing frida-server to emulator..."
adb push frida-server-${FRIDA_VERSION}-android-${ARCH} /data/local/tmp/frida-server

adb shell "chmod 755 /data/local/tmp/frida-server"

echo "Starting frida-server inside emulator..."
adb shell "/data/local/tmp/frida-server &"

echo "Frida-server setup completed."

if [ "$1" == "-w"]; then
  mitmweb -s traffic-analysis.py -p $PORT --set block_global=false
else
  mitmdump -s traffic-analysis.py -p $PORT --set block_global=false
fi

frida -U -f ${PACKAGE} -l multiple-script.js